name: Build and Start Backend and Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-start:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd smikkelweb-backend
          npm install
          cd ../smikkelweb-frontend
          npm install

      - name: Build backend
        run: |
          cd smikkelweb-backend
          npm run build

      - name: Build frontend
        run: |
          cd smikkelweb-frontend
          npm run build

      - name: Start backend
        run: |
          cd backend
          npm start

      - name: Start frontend
        run: |
          cd frontend
          npm start
