name: CI
on:
  push:
    branches:
      - main
  pull_request:

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: self-hosted
    container:
      image: ubuntu-latest
      ports:
        - 3000:3000
        - 3001:3001
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      #This line enables distribution
      - run: npm i
      - run: npm ci
      - run: npm run build
      - run: npx kill-port 127.0.0.1:3001
      - run: npx kill-port 127.0.0.1:3000
      - run: nohup npm run start-backend &
      - run: nohup npm run start-frontend &

      ## - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      ## - run: git branch --track main origin/main
